apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  namespace: devopslect
spec:
  selector:
    app: checkout-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30009
  type: NodePort
