FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
WORKDIR /app/product-service
RUN go build -o main ./cmd/main.go


FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/product-service/main .
EXPOSE 8080
CMD ["./main"]
