apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-backend
  namespace: devopslect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-backend
  template:
    metadata:
      labels:
        app: shop-backend
    spec:
      containers:
        - name: shop-backend
          image: fl012/webshop
          ports:
            - containerPort: 8080