apiVersion: v1
kind: Service
metadata:
  name: shop-backend-service
  namespace: devopslect
spec:
  selector:
    app: shop-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
  type: NodePort