apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: devopslect
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30010
  type: NodePort
