apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: devopslect
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008
  type: NodePort
