apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: devopslect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: fl012/product-service
          ports:
            - containerPort: 8080
