apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  namespace: devopslect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
        - name: checkout-service
          image: fl012/checkout-service
          ports:
            - containerPort: 8080
