apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: devopslect
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: fl012/auth-service
          ports:
            - containerPort: 8080
