name: Publish

on:
  push:
    tags:
      - '[A-Za-z0-9]+-service-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Get service name and version
        id: service
        run: |
          echo "service=$(echo ${{ github.ref }} | cut -d '/' -f 3 | cut -d '-' -f 1-2)" >> $GITHUB_OUTPUT
          echo "version=$(echo ${{ github.ref }} | cut -d '/' -f 3 | cut -d '-' -f 3)" >> $GITHUB_OUTPUT