name: Publish

on:
  push:
    tags:
      - '[A-Za-z0-9]+-service-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Get service name and version
        id: service
        run: |
          echo "service=$(echo ${{ github.ref }} | cut -d '/' -f 3 | cut -d '-' -f 1-2)" >> $GITHUB_OUTPUT
          echo "version=$(echo ${{ github.ref }} | cut -d '/' -f 3 | cut -d '-' -f 3)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-builds-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secretsDOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context:
          build-args: |
            service=${{ steps.service.outputs.service }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            &{{ github.actor }}/${{ steps.service.outputs.service }}:latest
            &{{ github.actor }}/${{ steps.service.outputs.service }}:${{ steps.service.outputs.version }}