name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.ACTION_KEY }}
          config-file: .github/workflos/release-please-config.json
          manifest-file: .github/workflos/.release-please-manifest.json